//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNCreator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Messages : global::System.Configuration.ApplicationSettingsBase {
        
        private static Messages defaultInstance = ((Messages)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Messages())));
        
        public static Messages Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("File with recent opened models not found !")]
        public string RecentOpenedModelsNotFound {
            get {
                return ((string)(this["RecentOpenedModelsNotFound"]));
            }
            set {
                this["RecentOpenedModelsNotFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cannot open help module")]
        public string CannotOpenHelp {
            get {
                return ((string)(this["CannotOpenHelp"]));
            }
            set {
                this["CannotOpenHelp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Delete selected objects ?")]
        public string DeleteObjects {
            get {
                return ((string)(this["DeleteObjects"]));
            }
            set {
                this["DeleteObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Do you want to exit ?")]
        public string ExitFromProgramm {
            get {
                return ((string)(this["ExitFromProgramm"]));
            }
            set {
                this["ExitFromProgramm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Service temporary unavailable !")]
        public string ServiceUnavailable {
            get {
                return ((string)(this["ServiceUnavailable"]));
            }
            set {
                this["ServiceUnavailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("File not found")]
        public string FileNotFound {
            get {
                return ((string)(this["FileNotFound"]));
            }
            set {
                this["FileNotFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Directory not found")]
        public string DirNotFound {
            get {
                return ((string)(this["DirNotFound"]));
            }
            set {
                this["DirNotFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Formula is correct. Calculated value =")]
        public string CorrectFormula {
            get {
                return ((string)(this["CorrectFormula"]));
            }
            set {
                this["CorrectFormula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The sintax of the formula is valid")]
        public string FormulaIsOK {
            get {
                return ((string)(this["FormulaIsOK"]));
            }
            set {
                this["FormulaIsOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The file of MPN Model has incorrect format")]
        public string WrongNetFileFormat {
            get {
                return ((string)(this["WrongNetFileFormat"]));
            }
            set {
                this["WrongNetFileFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You cannot connect these objects by choosen arc")]
        public string WrongPNObjectForArc {
            get {
                return ((string)(this["WrongPNObjectForArc"]));
            }
            set {
                this["WrongPNObjectForArc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name of the object was not found: ")]
        public string NameWasNotFound {
            get {
                return ((string)(this["NameWasNotFound"]));
            }
            set {
                this["NameWasNotFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This name already exists. Choose another one")]
        public string NameAlreadyExists {
            get {
                return ((string)(this["NameAlreadyExists"]));
            }
            set {
                this["NameAlreadyExists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Loops in formula are not allowed")]
        public string LoopAtFormula {
            get {
                return ((string)(this["LoopAtFormula"]));
            }
            set {
                this["LoopAtFormula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Simulation has been finished !")]
        public string SimulationFinished {
            get {
                return ((string)(this["SimulationFinished"]));
            }
            set {
                this["SimulationFinished"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Membrane {0} has already contains object with name {1}. Rename this object")]
        public string BadObjectForMembrane {
            get {
                return ((string)(this["BadObjectForMembrane"]));
            }
            set {
                this["BadObjectForMembrane"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Event handler must contain only one parameter of AbstractEventArgs class")]
        public string InvalidParametersCount {
            get {
                return ((string)(this["InvalidParametersCount"]));
            }
            set {
                this["InvalidParametersCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All unsave data will be lost. Do you want to proceed ?")]
        public string NewNet {
            get {
                return ((string)(this["NewNet"]));
            }
            set {
                this["NewNet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter simulation name (optionally)")]
        public string SimulationTextBoxTip {
            get {
                return ((string)(this["SimulationTextBoxTip"]));
            }
            set {
                this["SimulationTextBoxTip"] = value;
            }
        }
    }
}
